from homeassistant.components.sensor import SensorEntityDescription
from dataclasses import dataclass
import re

ADDRESS_API_URL = "https://api-adresse.data.gouv.fr"

CONF_CODE_POSTAL = "Code postal"
CONF_CITY = "city"
CONF_INSEE_CODE = "INSEE"
CONF_LOCATION_MAP = "location_map"
CONF_LOCATION_MODE = "location_mode"
CONF_ZONE_TYPE = "zone_type"
CONF_FOLLOW_HA_COORDS = "follow_ha_coords"

DEVICE_ID_KEY = "device_id"
DOMAIN = "vigieau"

GEOAPI_GOUV_URL = "https://geo.api.gouv.fr/communes?&fields=code,nom,centre"
HA_COORD = 0
ZIP_CODE = 1
SELECT_COORD = 2

LOCATION_MODES = {
    HA_COORD: "Coordonnées Home Assistant",
    ZIP_CODE: "Code Postal",
    SELECT_COORD: "Sélection sur carte",
}

LEVEL_COLORS = {
    0: "#e8edff",
    1: "#ffeda0",
    2: "#feb24c",
    3: "#fc4e2a",
    4: "#b10026",
}
NAME = "Vigieau"

VIGIEAU_API_URL = "https://api.vigieau.beta.gouv.fr"

ZONE_TYPES = {
    "SUP": "Eaux de surface",
    "AEP": "Alimentation en eau potable",
    "SOU": "Eaux souterraines",
}


@dataclass
class VigieEauRequiredKeysMixin:
    """Mixin for required keys."""

    category: str
    matchers: list[str]


@dataclass
class VigieEauSensorEntityDescription(
    SensorEntityDescription, VigieEauRequiredKeysMixin
):
    """Describes VigieEau sensor entity."""

    def match(self, usage: dict) -> bool:
        for matcher in self.matchers:
            if re.search(matcher, usage["usage"] + "|" + usage["thematique"]):
                return True
        return False


SENSOR_DEFINITIONS: tuple[VigieEauSensorEntityDescription, ...] = (
    VigieEauSensorEntityDescription(
        name="Alimentation des fontaines",
        icon="mdi:fountain",
        category="fountains",
        key="fountains",
        matchers=[
            "Surfaces accueillant des manifestations temporaires sportives et culturelles (motocross, festivals, comices, patinoires).*Arroser",
            "alimentation des fontaines.+",
            "douches .+ plage.+",
            "fontaines",
            "jeux d'eau",
            ".*Alimentation de douches de plage.*",
            "Remplissage citerne, reserve, cuve à eau",
        ],
    ),
    VigieEauSensorEntityDescription(
        name="Arrosage des jardins potagers",
        icon="mdi:watering-can",
        category="potagers",
        key="potagers",
        matchers=[
            "Arrosage des .*potagers",
            "Prélèvement pour le lavage de fruits.*",
        ],
    ),
    VigieEauSensorEntityDescription(
        name="Arrosage voirie et trottoirs",
        icon="mdi:road",
        category="roads",
        key="roads",
        matchers=[
            "Surfaces accueillant des manifestations temporaires.+sportives et culturelles.*Arroser",
            "trottoirs",
            "voiries|voieries",
            "Arrosage de surfaces de .+ générant de la poussière",
            "Nettoyage des voies publiques.+",
            "Arrosage des pistes de chantier",
            ".*voiries.*",
        ],
    ),
    VigieEauSensorEntityDescription(
        name="Arrosage des pelouses",
        icon="mdi:sprinkler-variant",
        category="lawn",
        key="lawn",
        matchers=[
            "Arrosage des massifs arbustifs publics et privés.*Arroser",
            ".*pelouses.*",
            "jardins d'agrément",
            "massifs fleuris",
            "Arrosage des espaces verts",
            "Arrosage des jeunes plantations d'arbres",
            "surface.+sportives.+",
            "arrosage.+massif.+",
            "Nettoyage / arrosage des sites de manifestations temporaires sportives et culturelles",
            "Dispositifs de récupération des eaux de pluie",
            "Arrosage, arbustes et arbres",
            "Arrosage des jardinières et suspensions",
            "Arrosage des espaces arborés",
            "Arrosage.+terrains de sport",
            "Arrosage terrain de sport et espaces verts",
            "Arrosage terrains sport.+",
            "Arrosage des îlots de fraîcheur validés par l’administration",
            "sols équestres et sports motorisés",
            "Arrosage des pistes d.hippodrome.*",
            "pistes de chevaux",
            ".*équestres.*",
            ".*motorisés.*",
            ".*motorisées.*",
            ".*Arrosage des jardins et parcs ouverts au public.*",
            ".*gazons.*",
            "Arrosage des terrains sportifs.+",
            "Potagers bac et jardin.*",
        ],
    ),
    VigieEauSensorEntityDescription(
        name="Lavage des véhicules",
        icon="mdi:car-wash",
        category="car_wash",
        key="car_wash",
        matchers=[
            "Lavage des véhicules par des professionnels.*Nettoyer",
            "Lavage des véhicules et engins professionnels.*Nettoyer",
            "Lavage des véhicules en station.*Nettoyer",
            "Lavage des véhicules des particuliers, hors des installations professionnelles.*Nettoyer",
            "Lavage des véhicules dans les stations de lavage.*Nettoyer",
            "Lavage des véhicules dans des installations professionnelles de lavage.*Nettoyer",
            "Lavage des véhicules chez les particuliers.*Nettoyer",
            "Lavage des véhicules chez les particuliers.*Nettoyer",
            "Lavage des véhicules.*Nettoyer",
            "Lavage des véhicules.*Nettoyer",
            "Lavage de véhicules.*Nettoyer",
            "Lavage de v.hicule(s)?( )?(chez les particuliers)?.*Nettoyer",
            "Lavage de véhicule en station de lavage disposant d’un système équipé d’un recyclage de l’eau.*.*Nettoyer",
            "Lavage de tous les véhicules et engins terrestres/nautiques dans des installations professionnelles.*Nettoyer",
            ".*lavage.+particuliers.*",
            "lavage.+professionnels.+portique",
            "lavage.+professionnels.+haute pression",
            "lavage.+(station|véhicules)",
            "lavage.+professionnel.+",
            "Nettoyage des véhicules et bateaux",
            "Nettoyage des véhicules, des bateaux Y compris par dispositifs mobiles",
            "Nettoyage des véhicules roulants.*",
            "Nettoyage des véhicules en station de lavage.*",
            "Nettoyage des véhicules.*",
        ],
    ),
    VigieEauSensorEntityDescription(
        name="Lavage des engins nautiques",
        icon="mdi:sail-boat",
        category="nautical_vehicules",
        key="nautical_vehicules",
        matchers=[
            ".*nautiques.*Travaux et activités en cours d'eau",
            "Nettoyage.+bateaux.*Nettoyer",
            "Lavage et rinçage de bateaux de plaisance par les particuliers.*Nettoyer",
            "Lavage des embarcations.*Nettoyer",
            "Douches de plage..*Nettoyer",
            "Activités nautiques : cas général",
            "lavage.+engins nautiques.+professionnels",
            "Nettoyage.+embarcation",
            "lavage.+bateau.+",
            "nettoyage.+bateau.+",
            "engins nautiques",
            "Lavage des embarcations, motorisées ou non, par tout moyen branché sur le réseau public",
            "Lavage de véhicule disposant d’un système équipé d’un recyclage de l’eau",
            "Carénage des bateaux",
            "Lavage et entretien des embarcations .+ en aire de carénage.",
            "lavage.*embarcation.*",
        ],
    ),
    VigieEauSensorEntityDescription(
        name="Lavage des toitures, façades",
        icon="mdi:home-roof",
        category="roof_clean",
        key="roof_clean",
        matchers=[
            "Nettoyage de terrasses.*Nettoyer",
            "Nettoyages des facades, murs, toits, terrasses et travaux.*Nettoyer",
            "Nettoyage extérieur des bâtiments et à l'eau des chaussées,caniveaux,surfaces ext imperméabilisées.*Nettoyer",
            "Nettoyage de terrasses, de cours, de petits ouvrages*Nettoyer",
            "Nettoyage de bâtiments, hangars, locaux de stockage.*Nettoyer",
            "Nettoyage de bâtiments, hangars et autres surfaces imperméabilisées.*Nettoyer",
            "toitures",
            "façades",
            "nettoyage.+bâtiments.+",
            "nettoyage.+terrasse.+",
        ],
    ),
    VigieEauSensorEntityDescription(
        name="Vidange et remplissage des piscines",
        icon="mdi:pool",
        category="pool",
        key="pool",
        matchers=[
            "Piscines.*Remplir ou vidanger",
            "Piscines non collective de plus de 1m3.*Remplir ou vidanger",
            "Piscines familiales privées, dont bains à remous, et communes en résidences privées.*Remplir ou vidanger",
            "Piscines et autres structures de volume > 1m3 privés ou publics à usage collectif.*Remplir ou vidanger",
            "Piscines accueillant du public.*Remplir ou vidanger",
            "remplissage.+piscines.+(familial|privé)",
            "vidange.+piscines",
            "piscines privées",  # Piscines privées et bains à remous de plus de 1m3
            "piscine à usage collectif",
            "piscine(s)? non collective",  # Remplissage et vidange de piscines non collectives (de plus de 1 m3)
            "baignades.+",
            "Remise à niveau des piscines à usage privé",
            "Remplissage des jeux d'eau",
            "jeux d.eau",
            "Remplissage des piscine privées",
            "Remplissage des piscines individuelles",
            "remise à niveau des piscines",
            "Remplissage de piscines.+",
            "Piscines ouvertes au public.*",
            "Remplissage des piscines.+publi",
            "Remplissage des jacuzzis",
            ".*piscines.*",
            ".*tobbogan aquatique.*",
            "Remplissage et appoint des bassins individuels dans les établissements recevant.*",
        ],
    ),
    VigieEauSensorEntityDescription(
        name="Remplissage/Vidange des plans d'eau",
        icon="mdi:waves",
        category="ponds",
        key="ponds",
        matchers=[
            "pêches électriques.*Travaux et activités en cours d'eau",
            "Vidanges des plans d’eau et/ou manœuvres de vannage.*Remplir ou vidanger",
            "Vidanges de plan d'eau.*Remplir ou vidanger",
            "Vidange totale de plans d’eau vers le réseau hydrographique.*Remplir ou vidanger",
            "Vidange totale de plans d'eau vers le réseau hydrographique.*Remplir ou vidanger",
            "Vidange plans d’eau vers le réseau hydrographique.*Remplir ou vidanger",
            "Vidange des plans d’eau quelque soit leur taille.*Remplir ou vidanger",
            "Vidange des plans d’eau.*Remplir ou vidanger",
            "Vidange des plans d'eau, étangs, bassins d'agrément.*Remplir ou vidanger",
            "Vidange des plans d'eau.*Remplir ou vidanger",
            "Vidange des plans d'eau.*Remplir ou vidanger",
            "Vidange de plans d’eau vers le réseau hydrographique.*Remplir ou vidanger",
            "Vidange de plans d’eau de toute nature vers le réseau hydrographique.*Remplir ou vidanger",
            "Vidange de plans d’eau.*Remplir ou vidanger",
            "Vidange de plans d'eau vers le réseau hydrographique.*Remplir ou vidanger",
            "Vidange de plan d'eau à usage non domestique.*Remplir ou vidanger",
            "Vidange de plan d'eau pour usage domestique.*Remplir ou vidanger",
            "Remplissages des retenues d’irrigation.*Irriguer",
            "Remplissage/Vidange des plans d'eau installés sur des cours d'eau ou alimentés par des sources.*Remplir ou vidanger",
            "Remplissage/Vidange des plans d'eau de loisir.*Remplir ou vidanger",
            "Remplissage/Vidange des plans d'eau alimentés en dérivation, usage économique.*Remplir ou vidanger",
            "Remplissage ou mise à niveau des plans d’eau à vocation cynégétique.*Remplir ou vidanger",
            "Remplissage ou mise à niveau des plans d’eau.*Remplir ou vidanger",
            "Remplissage ou maintien du niveau des plans d’eau de loisir à usage personnel.*Remplir ou vidanger",
            "Remplissage et appoints en eau des plans d'eau.*Remplir ou vidanger",
            "Remplissage des retenues d'irrigation.*Irriguer",
            "Remplissage des plans d’eau.*Remplir ou vidanger",
            "Remplissage des plans d'eau, hors tonnes de chasse.*Remplir ou vidanger",
            "Remplissage des plans d'eau sauf retenues destinées à l'AEP et retenues participant au soutien d'éti.*Remplir ou vidanger",
            "Remplissage des plans d'eau d'agrément et des canaux d'agrément.*Remplir ou vidanger",
            "Remplissage des plans d'eau.*Remplir ou vidanger",
            "Remplissage de plans d’eau sauf destinés à l’AEP et soutien d’étiage permis par arrêté.*Remplir ou vidanger",
            "Remplissage de plan d'eau.*Remplir ou vidanger",
            "Prélèvements à usage non domestique dans les plans d'eau en travers de cours d'eau.*Prélever",
            "Nettoyage des réservoirs d’eau potable.*Nettoyer",
            "Alimentation .+plan(s)? d.eau.+",
            "Alimentation de bassins pour l’agrément des animaux, dont le manque d’eau est susceptible de présenter des risques.*Remplir ou vidanger",
            "remplissage.+plan.* d.eau",
            "vidange.+plan.* d.eau",
            "Alimentation de plan d'eau",  # Alimentation de plan d'eau en dérivation de cours d'eau à usage domestique
            "alimentation.+plan.* d.eau",
            "alimentation.+bassin.+",
            "lestage pour stabilité",
            "Alimentation d’étangs",
            "remplissage.*retenues.*",
            "Alimentation des retenues collinaires",
            "Remplissage des réserves",
            "Remplissage des réserves  incendie",
        ],
    ),
    VigieEauSensorEntityDescription(
        name="Travaux sur cours d'eau",
        icon="mdi:hydro-power",
        category="river_rate",
        key="river_rate",
        matchers=[
            "Travaux/rejet en cours d’eau.*Travaux et activités en cours d'eau",
            "Travaux sur les STEP ou sur les postes susceptible d’occasionner des rejets dans les cours d'eau.*Travaux et activités en cours d'eau",
            "Travaux sur cours d'eau.*Travaux et activités en cours d'eau",
            "Travaux ou activités en lit mineur de cours d’eau.*Travaux et activités en cours d'eau",
            "Travaux en rivières, zones de chantier en eau ou en zone de protection.*Travaux et activités en cours d'eau",
            "Travaux en rivières zones de chantier hors eau.*Travaux et activités en cours d'eau",
            "Travaux en lit mouillé d’un cours d’eau.*Travaux et activités en cours d'eau",
            "Travaux en cours d’eau..*Travaux et activités en cours d'eau",
            "Travaux en cours d’eau.*Travaux et activités en cours d'eau",
            "Travaux en cours d’eau.*Travaux et activités en cours d'eau",
            "Travaux en cours d’eau.*Travaux et activités en cours d'eau",
            "Travaux en cours d'eau et voies d'eau.*Travaux et activités en cours d'eau",
            "Travaux en cours d'eau entraînant prélèvements/rejets d'eau polluées.*Travaux et activités en cours d'eau",
            "Travaux en cours d'eau.*Travaux et activités en cours d'eau",
            "Travaux dans le lit du cours d’eau.*Travaux et activités en cours d'eau",
            "Travaux dans le lit du cours d'eau.*Travaux et activités en cours d'eau",
            "Orpaillage.*Travaux et activités en cours d'eau",
            "Loisirs nautiques en eau douce hors pêche.*Travaux et activités en cours d'eau",
            "Gestion des écluses de navigation.*Travaux et activités en cours d'eau",
            "Alimentation de plans d'eau en dérivation ayant un usage de loisir à usage personnel.*Remplir ou vidanger",
            "Alimentation de canaux par des cours d'eau.*Remplir ou vidanger",
            "Activités de loisirs professionnelles ou amateurs en cours d’eau..*Travaux et activités en cours d'eau",
            "Activités  en rivière impliquant la circulation, le passage et le piétinement dans les cours d’eau dont activités sportives.*Travaux et activités en cours d'eau",
            "ouvrage.+cours d.eau",
            "travaux.+cours d.eau",
            "manoeuvre.+vannes",  # Manoeuvre de vannes des seuils et barrages
            "Gestion des ouvrages",  # FIXME: we should probably match with the category as well
            "travaux.+rivière",
            "rabattement.+nappe.+",
            "faucardage.+",
            "Faucardement",
            "manoeuvre.+d.ouvrage.+",
            "rejet direct d’eaux polluées",
            "Rejets des STEU et des collecteurs pluviaux",
            "orpaillage",
            "Manœuvres des vannes d.installations hydrauliques",
            "Installations de production d’électricité hydraulique",
            "Installation de production d'électricité hydraulique et termique à flamme",
            "Manœuvres d’ouvrages hydrauliques",
            "Tout usage domestique non sanitaire de l’eau",
            "Réalisation d'un seuil provisoire",
            "Rejets directs en cours d’eau",
            "Pratiques ou activités dans le lit pouvant avoir un impact sur les milieux aquatiques",
            "Perturbations physiques du lit des cours d’eau",
            "Entretien de cours d'eau",
            "Travaux et rejets",
            "Travaux sur les systèmes d’assainissement occasionnant des rejets",
            ".*installations hydrauliques.*",
            ".*électricité d’origine hydraulique.*",
            "Installations hydroélectriques",
            "production.+origine.+hydraulique.*",
            ".*hydroélectriques.*",
            ".*hydrauliques.*",
            "Installations de production d'électricité d'orignie hydraulique",
            "Prélèvements des centrales hydroélectriques, moulins, barrages",
            "Installations de production d'électricité hydraulique.*",
            "Installations de production d’électricité d’origine nucléaire",
            "Prélèvement domestique directement dans le cours d'eau",
            "Prélèvements pour la production d’eau potable",
            "Prélèvements d’eau dans les lavoirs",
            "Prélèvement d’eau superficielle.+",
            "Création de prélèvement.*",
            "Essai de pompage",
            "Production d'eau potable",
            "Gestion des niveaux d’eau des plans en dérivation.*",
            "Prélèvement dans les eaux souterraines.*",
            "Rejets dans le milieu naturel",
            "Réseau d'adduction d'eau potable",
            "Alimentation du Canal de la Sauldre et du Canal latéral à la Loire",
            "Alimentation des prises d'eau réglementées du canal de Berry",
            "Alimentation des prises d'eau non réglementées du Canal de Berry",
        ],
    ),
    VigieEauSensorEntityDescription(
        name="Navigation fluviale",
        icon="mdi:ferry",
        category="river_movement",
        key="river_movement",
        matchers=[
            "navigation fluviale sur le bassin Seine Normandie.*Travaux et activités en cours d'eau",
            "navigation fluviale sur le bassin Loire Bretagne.*Travaux et activités en cours d'eau",
            "Navigation fluviale",
            "Pratique du canyoning sur matériaux alluvionnaires",
            "Pratique de la navigation de loisir",
        ],
    ),
    VigieEauSensorEntityDescription(
        name="Arrosage des golfs",
        icon="mdi:golf",
        category="golfs",
        key="golfs",
        matchers=[
            "arrosage des golfs",
            "Arrosage des.+golfs",
            "parcours de golf",
            "greens et départs",
            ".*golf.*",
        ],
    ),
    VigieEauSensorEntityDescription(
        name="Prélèvement en canaux",
        icon="mdi:water-pump",
        category="canals",
        key="canals",
        matchers=[
            "Prélèvement dans le canal.*Prélever",
            "Alimentation gravitaire des ouvrages d’irrigation et des canaux d'agrément dans la Lozère.*Remplir ou vidanger",
            "Alimentation gravitaire des canaux d’agrément.*Remplir ou vidanger",
            "Alimentation des canaux de navigation.*Prélever",
            "Prélèvement en canaux",
            "Prélèvements dans le milieu naturel.+",
            "prélèvements.+cours d.eau.+",
            "prélèvement.+hydraulique.+",
            "alimentation.+canaux.+",
            "Prélèvements domestiques directs dans les milieux hydrauliques, hors usage professionnel identifié",
            "Prélèvement d’eau domestique en milieu",
            "Prélèvement d’eau domestique dans un canal existant",
            "Prélèvements énergétiques",
            "Prélèvement.* en cours d'eau",
            "Prélèvements destinés au fonctionnement des milieux naturels",
            "Prélèvement sur le site des Marais de Sacy",
            "Tout nouveau prélèvement",
            "Nouvelles demandes de prélèvement d'eau et création de forages",
            "Création de prélèvements",
            "Prélèvement en cours d’eau",
            "alimentation en eau potable des populations.+",
            "Prélèvement dans les cours d'eau quelque soit l'usage",
            ".*forages.*",
            "forage domestique",
            "prélèvement dans un cours d.eau",
        ],
    ),
    VigieEauSensorEntityDescription(
        name="Arrosage des arbres et plantes",
        category="mdi:tree",
        key="trees",
        matchers=[
            "Cultures en godets et semis.*Arroser",
            ".*arbres.*",
            "Irrigation pour jeunes plantations d'arbres ou arbustes de moins de 5 ans..*Irriguer",
            ".*horticulture.*",
            "Irrigation horticulture, jeunes plants, vergers, plantes médicinales ou aromatiques.*Irriguer",
            "Irrigation des cultures maraîchères, production de semences, arboriculture, culture des fruits rouge.*Irriguer",
            "Irrigation des cultures maraîchères en godets ou repiquées, cultures horticoles ou cultures hors-sol.*Irriguer",
            "Irrigation des cultures horticoles hors sol.*Irriguer",
            "Irrigation des cultures de semences, horticulture, maraîchage, pépinière, jeunes plants < 1 an.*Irriguer",
            "Irrigation des autres cultures.*Irriguer",
            "Irrigation des arbres et arbustes plantés en pleine terre depuis moins de 2 ans.*Irriguer",
            "Cultures sous serre et jeunes plants en pépinière dont jardinerie.*Irriguer",
            "Arrosage en jardinerie.*Arroser",
            "Arrosage des plantes sous serre.*Arroser",
            "Arrosage des petits fruits.*Irriguer",
            "Arrosage des jardineries.*Arroser",
            "Arrosage de plantes et de fleurs des jardineries, des fleuristes, des pépiniéristes, ....*Arroser",
            "Arrosage de jeunes plants ligneux.*Arroser",
            "Arrosage.+ arbres.+",
            "Arrosage de jardineries.+",
            "Arrosage de.+ plantat.+",
            "irrigation.*arbres.*",
            "Jardinerie",
            "Irrigation pour jeunes arbustes et plantiers de vigne",
        ],
    ),
    VigieEauSensorEntityDescription(
        name="Usage pour animaux",
        category="mdi:cow",
        key="animals",
        matchers=[
            "Arrosage des pistes pour chevaux.*Arroser",
            "Abreuvement et hygiène des animaux",
            "Abreuvement des animaux",
            "Besoins pour les animaux",
        ],
    ),
    VigieEauSensorEntityDescription(
        name="Maraîchage et cultures",
        category="mdi:corn",
        key="fields",
        matchers=[
            "Irrigations des cultures - prélèvements directs rivière, canal de Bourgogne....*Irriguer",
            "Prélèvements à usage non domestique dans les plans d'eau en travers de cours d'eau.*Prélever",
            "Irrigation prairies, grandes cultures, cultures de plein champ.*Irriguer",
            "Irrigation gravitaire ou par aspersion des cultures.*Irriguer",
            "Irrigation grandes cultures .+ avec système d’irrigation localisée.*Irriguer",
            "Irrigation des prairies, grandes cultures, cultures de plein champ.*Irriguer",
            "Irrigation du maraîchage.*Irriguer",
            "Irrigation ds cultures non-spécialisées.*Irriguer",
            "Irrigation des semis en maraîchage.*Irriguer",
            "Irrigation des replantations en maraîchage.*Irriguer",
            "Irrigation des productions maraîchères professionnelles.*Irriguer",
            "Irrigation des prairies de graminées à partir d'une retenue en travers de cours d'eau.*Irriguer",
            "Irrigation des prairies de graminées.*Irriguer",
            "Irrigation des grandes cultures, prairies.*Irriguer",
            # regexp to match maraichage except if prefixed by "hors"
            ".*(?!hors).*mara.(chage|chère).*",
            "Irrigation des cultures par aspersion.*Irriguer",
            "Irrigation des cultures maraîchères de plein champ.*Irriguer",
            "Irrigation des cultures maraîchères.*Irriguer",
            "Irrigation des cultures intermédiaires à valorisation énergétique.*Irriguer",
            "Irrigation des cultures.*Irriguer",
            "Irrigation des cultures.*Irriguer",
            "Irrigation de grandes cultures .+sans système d’irrigation localisée.*Irriguer",
            "Irrigation Agricole - Bassin du Gave d'Oloron.*Irriguer",
            "Arrosage des haies plantées depuis moins de 2 ans en secteur rural.*Arroser",
            "Arrosage des cultures maraîchères, cultures horticoles, cultures hors-sol ou sous abris.*Arroser",
            "agricole",
            "Irrigation par aspersion.*",
            "Irrigation par submersion",
            "Irrigation des serres.*",
            "irrigation.*cultures.*",
            "irrigation.*maraîch.*",
            "Maraîchage",
            "irrigation.*horticulture.*",
            "Horticulture",
            "Irrigation par système localisé et équipé d’un outil de pilotage",
            "Irrigation par système d'irrigation localisée.*",
            "Cultures sensibles",
            "Cultures maraîchère",
            "Prélèvement pour réseau d'irrigation collective",
            "Irrigation dans le cadre de la gestion collective",
            "Prélèvements.*horticulture.*",
        ],
    ),
    VigieEauSensorEntityDescription(
        name="Restriction spécifique",
        category="misc",
        key="misc",
        matchers=[
            "autres prélèvements dans le milieu naturel.*Prélever",
            "Usages de l’eau strictement nécessaires au process de production ou à l’activité exercée.*Activités économiques",
            "Usages de l’eau strictement non nécessaires au process de production ou à l’activité exercée.*Activités économiques",
            "Usages de l'eau strictement nécessaires au process de production ou à l'activité exercée.*Activités économiques",
            "Usages de l'eau non nécessaires au process de production ou à l'activité exercée.*Activités économiques",
            "Usage de l'eau strictement nécessaire au process de production ou à l'activité exercée.*Activités économiques",
            "Usage de l'eau non strictement nécessaire au processus de production ou à l'activité exercée.*Activités économiques",
            "Usage de l'eau non directement lié au process industriel ou non indispensable à l'activité.*Activités économiques",
            "Travaux avec rejet d'assainissement dépassant les normes autorisées.*Travaux et activités en cours d'eau",
            "Travaux avec rejet d'assainissement dépassant les normes autorisées.*Travaux et activités en cours d'eau",
            "Stations d’épuration et systèmes d’assainissement.*Rejeter",
            "Stations d’épuration.*Rejeter",
            "Stations d'épuration et systèmes d'assainissement.*Nettoyer",
            "Stations d'épuration et systèmes d'assainissement.*Rejeter",
            "Stations d'épuration.*Rejeter",
            "Station de traitement des eaux usées et leur travaux d’entretien.*Rejeter",
            "Station d'épuration.*Rejeter",
            "STEP.*Activités économiques",
            "Remplissage/alimentation des structures gonflables ou tubulaires publiques et privées ERP de plus de 1m3.*Remplir ou vidanger",
            "Rejets.*Rejeter",
            "Pêches électriques de suivi et d’inventaire.*Travaux et activités en cours d'eau",
            "Pêches scientifiques.*Travaux et activités en cours d'eau",
            "Pêche en eau douce.*Travaux et activités en cours d'eau",
            "Pêche.*Travaux et activités en cours d'eau",
            "Prévention ou lutte contre les incendies.*Sécurité incendie",
            "Process des activités industrielles, commerciales et artisanales consommant plus de 1000m3/an prélevés au milieu OU plus de 7000m3/an en total prélevé.*Activités économiques",
            "Process consommant plus de 1000m3/an prélevés dans le milieu OU plus de 7000m3/an au total.*Activités économiques",
            "Process consommant moins de 1000m3/an dans le milieu ET moins de 7000m3/an au total.*Activités économiques",
            "Pratique de la pêche.*Travaux et activités en cours d'eau",
            "Orpaillage, cheminement à pied dans le vif des cours d’eau.*Travaux et activités en cours d'eau",
            "Orpaillage, cheminement à pied dans le vif des cours d'eau.*Travaux et activités en cours d'eau",
            "Orpaillage, cheminement à pied dans le lit vif des cours d'eau.*Travaux et activités en cours d'eau",
            "Orpaillage et pêche à l’aimant..*Travaux et activités en cours d'eau",
            "Orpaillage et pratiques pouvant impacter les milieux aquatiques.*Travaux et activités en cours d'eau",
            "Orpaillage.*",
            "Organisations collectives d’irrigation: asso. syndicales, collectivités, groupement d'agriculteurs.*Irriguer",
            "Manœuvre des bornes d’incendie.*Sécurité incendie",
            "Aspersion relevant d'un régime d'autorisation ou déclaration R214-1.*Irriguer",
            "Forages.*Prélever",
            "Entreprises soumises à un APC relatif à la sécheresse.*Activités économiques",
            "Contrôle technique des points d'eau incendie.*Sécurité incendie",
            "Centres nucléaires de production d’électricité.*Installations de production d'électricité",
            "Autres usages des poteaux incendie.*Sécurité incendie",
            "Autres prélèvements dans le milieu naturel.*Prélever",
            "Alimentation en eau potable.+",
            "Gestion des systèmes d'assainissement",
            "Remplissage tonne de chasse",
            "Activités cynégétiques",
            "Structures gonflables/tubulaires privées à usage collectif > 1m3 nécessitant 1 vidange quotidienne",
            "Irrigation gravitaire et aspersion",
            "Irrigation par canal gravitaire",
            "Irrigation en Période de Printemps",
            "Irrigation en Période Estivale",
            "Irrigation Période Estivale",
            "Irrigation OUGC",
            "CIVE",
            "CIPAN*",
            "Irrigation dans les unités de gestion souterraines ou les grands cours d'eau",
            "Irrigation dans le cadre de la gestion collective des associations d’irrigants",
            "Irrigation dans le cadre de la gestion collective Vie aval pilotée par la Chambre d'agriculture",
            "Prélèvements pour l’irrigation assimilés domestiques",
            "Prélèvements hors irrigation",
            "grumes",
            # ICPE means "Installation classée pour la protection de l'environment"
            "ICPE",
            "ICPE soumises à un APC relatif à la sécheresse",
            "Usages récréatifs collectifs à partir d’eau potable.+",
            "Réalisation de seuils provisoires",
            "Activités industrielles et commerciales",
            "Interventions sur Station d'épuration",
            "station.*épuration",
            "station.*traitement.*eaux.*usées",
            ".*industriels.*",
            "remplissage.*neige.*",
            "Production de neige",
            "neige de culture",
            "des enneigeurs",
            "usage.*non directement.*process.*",
            "usage.*nécessaire.*process.*",
            "usages agricoles",
            "Activités industrielles.*",
            "Activités commerciales.*",
            "Activités artisanales, commerciales et industrielles",
            "Établissements ayant une faible consommation d'eau",
            "Vente de plantations",
            "Prélèvements d’eau à usage industriel.*",
            "Prélèvement dans le canal pour un usage économique",
            "lavage.*réservoirs d'eau potable",
            "Lavage des réservoirs",
            "période d'étiage",
            "Irrigation à partir de retenues d’eau autorisées remplies hors période d’étiage",
            "Irrigation par des eaux brutes provenant des ressources dites « maîtrisées »",
            "Industries",
            "Arboriculture en technique économe",
            "Uniquement en Nouvelle Aquitaine",
            "Purge des réseaux",
            "Installations thermiques à flamme",
            "Béalières et canaux d’irrigation alimentés par gravité ou par pompage",
            "Autres prélèvements à usage industriel ou artisanal",
            "Autre irrigation",
            "Contrôles périodiques des points d.eau d’incendie",
            "Réservoirs eau potable",
            "Alimentation en eau des populations.+",
            "Besoins prioritaires.+",
            "Contrôle des bornes d’incendie.*",
            "Eau de Paris",
            "Autres usages publics non cités.*",
            "Autres usages professionnels non cités",
            "Autres usages des particuliers non cités",
        ],
    ),
)
